### ISSUE TITLE
Document Windows compatibility

### ISSUE THREAD

**Issue by shuchitak** [xmos/fwk_voice#222]
sw_avona examples and modules are now Windows compatible. Windows support related documentation needs to be added.

**Comment by mbanth** [comment]
According to @keithm-xmos, the examples in the XCore SDK all build on Windows.  Each README shows the commands for Mac/Linux and Windows.  CMake handles most of the differences in building on different platforms.  Some examples use utilities that do not support Windows.  The IoT example is one, and may be the only one, with this limitation.  Where such a limitation exists, the README notes that it exists.

It sounds like moving the documentation for platform build support to a single location will require additional work.  Until we have a decision on where this information should live, work on this issue is blocked.
