### ISSUE TITLE
Moving core aec into a shared adaptive_filter infrustrusture

### ISSUE THREAD

**Issue by uvvpavel** [xmos/fwk_voice#292]
After talking to @shuchitak, we decided that it would be beneficial to move the core aec code into a shared infrastructure which will be shared between aec and ic. This makes more sense and should be easier to maintain

**Comment by shuchitak** [comment]
I would give this a size label L since this will involve moving the tests as well. I also want to consider changing the tests to test against the python model instead of double precision reference C implementation as part of this. However doing that would also need a refactor of the python model into functions we can test again. We'll also need to consider where these python model functions might be. Since this is a shared library in avona, it would make sense to compare it to a similar shared library in py_avona when it exists? Something to think about.

**Comment by mbanth** [comment]
> I would give this a size label L since this will involve moving the tests as well ....
If the work is that extensive, please decompose it into smaller issues.

**Comment by uvvpavel** [comment]
@mbanth this issue needs some planning and discussion, after that we can decompose it into smaller issues. I assume this will be a long term plan since it would involve some restructuring from the acoustic side as well. When these discussions will take place we are likely to delete this issue and make a lot of small ones.

**Comment by uvvpavel** [comment]
Closing this issue as it was split into a series of smaller ones
