### ISSUE TITLE
Use shared adaptive filter in lib_ic

### ISSUE THREAD

**Issue by hughh-xmos** [xmos/fwk_voice#362]

**Comment by mbanth** [comment]
I'm unsure of the purpose or scope of this issue since lib_interference_canceller already uses a shared adaptive filter implementation, namely the one in the Voice Toolbox (lib_voice_toolbox).  Given that lib_interference_canceller is only used in applications that are either in maintenance phase or soon will be, I do not see a business case to enhance this implementation of the IC.

**Comment by hughh-xmos** [comment]
i dont think there will be any changes to lib_interference_canceller (as in the old separate repo) is that what you mean?

this is about fwk_voice/modules/lib_ic using the shared adaptive filter as described in issue 356

**Comment by mbanth** [comment]
> i dont think there will be any changes to lib_interference_canceller (as in the old separate repo) is that what you mean?
> 
> this is about fwk_voice/modules/lib_ic using the shared adaptive filter as described in issue 356

I understand now.  I mis-interpreted 'lib_ic' to mean the old lib_interference_canceller.

**Comment by mbanth** [comment]
A review by @andrewdewhurst and myself has concluded that we will not work on this issue.
